server.port=8080
spring.application.name=productos-service

# URLs de los microservicios internos
services.catalog.url=http://localhost:8082
services.discount.url=http://localhost:8081

# Puerto de gestión (opcional, recomendado para producción)
management.server.port=8091

# Exponer el endpoint de Prometheus (y otros si es necesario)
management.endpoints.web.exposure.include=prometheus,health,metrics

# Etiqueta global con el nombre de la aplicación
management.metrics.tags.application=productos-service