server.port=8082
spring.application.name=catalogo-service

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/catalogo_db
spring.datasource.username=bootcamp_user
spring.datasource.password=bootcamp_password_sec2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Puerto de gestión (opcional, recomendado para producción)
management.server.port=8091

# Exponer el endpoint de Prometheus (y otros si es necesario)
management.endpoints.web.exposure.include=prometheus,health,metrics

# Etiqueta global con el nombre de la aplicación
management.metrics.tags.application=catalogo-service